# Generated by Django 6.0.2 on 2026-03-24 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('IMPORT', 'Imported'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('PASSWORD_CHANGE', 'Changed Password'), ('SETTINGS_CHANGE', 'Changed Settings'), ('BULK_DELETE', 'Bulk Deleted'), ('STATUS_CHANGE', 'Changed Status')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dashboard_a_timesta_915d4e_idx'), models.Index(fields=['user', '-timestamp'], name='dashboard_a_user_id_c5016c_idx'), models.Index(fields=['action', '-timestamp'], name='dashboard_a_action_658683_idx'), models.Index(fields=['model_name', 'object_id'], name='dashboard_a_model_n_cbb3c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('budget', 'Budget'), ('expense', 'Expense'), ('fund', 'Fund'), ('deadline', 'Deadline'), ('system', 'System')], default='system', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('event_key', models.CharField(blank=True, db_index=True, help_text='Optional deduplication key for recurring alerts', max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Notification recipient', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='dashboard_a_user_id_c44dd5_idx'), models.Index(fields=['event_key', 'created_at'], name='dashboard_a_event_k_489a88_idx')],
            },
        ),
    ]
