# Generated by Django 5.2.11 on 2026-02-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
                ('tin', models.CharField(max_length=50)),
                ('philgeps_registration', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('proprietor', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
    ]
