# Generated by Django 5.2.11 on 2026-02-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('NV', 'NV'), ('V', 'V')], default='NV', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat_status',
            field=models.CharField(default='NV', max_length=200),
            preserve_default=False,
        ),
    ]
