# Generated by Django 5.2.11 on 2026-02-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_supplier_category_supplier_vat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='vat_status',
        ),
    ]
