# Generated by Django 5.2.11 on 2026-02-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_remove_supplier_vat_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='category',
            new_name='vat_status',
        ),
    ]
