# Generated by Django 5.2.11 on 2026-02-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_rename_category_supplier_vat_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='proprietor',
            new_name='propprietor',
        ),
    ]
