# Generated by Django 5.2.11 on 2026-02-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_rename_proprietor_supplier_propprietor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fund_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='dashboard_app.fundsource')),
            ],
        ),
    ]
