# Generated by Django 5.2.11 on 2026-02-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_fundsource_budgetbreakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('check_number', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Cleared', 'Cleared'), ('On Process', 'On Process')], max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
    ]
