# Generated by Django 5.2.11 on 2026-02-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_bankstatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='contact_number',
        ),
    ]
