# Generated by Django 5.2.11 on 2026-02-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_remove_bankstatement_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
