# Generated by Django 5.2.11 on 2026-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0010_alter_bankstatement_check_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
