# Generated by Django 6.0.2 on 2026-02-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_rename_name_staff_first_name_staff_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFundMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=100)),
                ('fund_source', models.CharField(max_length=100)),
                ('mooe', models.CharField(max_length=100)),
                ('nc', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('payee', models.CharField(max_length=255)),
                ('particulars', models.TextField()),
                ('tin', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_type', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_type', models.CharField(blank=True, max_length=100, null=True)),
                ('downloads', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('payments', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('dv_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('account_title', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_5_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('services_5_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('goods_services_3_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('goods_1_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('services_2_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('rental_5_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('prof_fee_10_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('expense_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared'), ('Bounced', 'Bounced')], default='Pending', max_length=20)),
                ('staff', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_5_percent_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('services_5_percent_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('goods_services_1_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('goods_1_percent_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('services_2_percent_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('rental_5_percent_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('prof_fee_10_percent_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Fund Monitoring',
                'verbose_name_plural': 'Master Fund Monitorings',
                'ordering': ['-date'],
            },
        ),
    ]
