# Generated by Django 6.0.2 on 2026-02-27 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0012_masterfundmonitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfundmonitoring',
            name='fund_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='dashboard_app.fundsource'),
        ),
        migrations.AlterField(
            model_name='masterfundmonitoring',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='dashboard_app.supplier'),
        ),
    ]
