# Generated by Django 6.0.2 on 2026-02-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0013_alter_masterfundmonitoring_fund_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='vat_status',
            field=models.CharField(choices=[('NV', 'NV'), ('V', 'V'), ('NA', 'N/A')], max_length=2),
        ),
    ]
