# Generated by Django 6.0.2 on 2026-02-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0015_expensecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetBreakdown',
        ),
    ]
