# Generated by Django 6.0.2 on 2026-02-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0016_delete_budgetbreakdown'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseCategory',
            new_name='ExpenseObject',
        ),
    ]
