# Generated by Django 6.0.2 on 2026-02-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0017_rename_expensecategory_expenseobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseobject',
            options={'ordering': ['code'], 'verbose_name': 'Expense Object', 'verbose_name_plural': 'Expense Objects'},
        ),
    ]
