# Generated by Django 6.0.2 on 2026-02-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0020_expensecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfundmonitoring',
            name='expense_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_expenses', to='dashboard_app.expensecategory'),
        ),
    ]
