# Generated by Django 6.0.2 on 2026-02-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0021_alter_masterfundmonitoring_expense_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfundmonitoring',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_records', to='dashboard_app.staff'),
        ),
    ]
