# Generated by Django 6.0.2 on 2026-02-28 12:51

import django.db.models.deletion
from django.db import migrations, models


def create_divisions_from_staff(apps, schema_editor):
    """Create Division objects from existing Staff division values"""
    Staff = apps.get_model('dashboard_app', 'Staff')
    Division = apps.get_model('dashboard_app', 'Division')
    
    # Get unique divisions from Staff
    unique_divisions = Staff.objects.values_list('division', flat=True).distinct()
    
    for division_name in unique_divisions:
        if division_name:
            Division.objects.get_or_create(name=division_name, defaults={'is_active': True})


def populate_staff_division_fk(apps, schema_editor):
    """Populate the staff division_id with Division IDs"""
    Staff = apps.get_model('dashboard_app', 'Staff')
    Division = apps.get_model('dashboard_app', 'Division')
    
    for staff in Staff.objects.all():
        try:
            division = Division.objects.get(name=staff.division)
            staff.division_id = division.id
            staff.save()
        except Division.DoesNotExist:
            pass


def populate_monitoring_division_fk(apps, schema_editor):
    """Populate the masterfundmonitoring division_id with Division IDs"""
    MasterFundMonitoring = apps.get_model('dashboard_app', 'MasterFundMonitoring')
    Division = apps.get_model('dashboard_app', 'Division')
    
    for monitoring in MasterFundMonitoring.objects.all():
        try:
            division = Division.objects.get(name=monitoring.division)
            monitoring.division_id = division.id
            monitoring.save()
        except Division.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0022_alter_masterfundmonitoring_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_divisions_from_staff),
        # Add FK fields to Staff and MasterFundMonitoring
        migrations.AddField(
            model_name='staff',
            name='division_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='dashboard_app.division'),
        ),
        migrations.AddField(
            model_name='masterfundmonitoring',
            name='division_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_records', to='dashboard_app.division'),
        ),
        # Populate the new FK fields
        migrations.RunPython(populate_staff_division_fk),
        migrations.RunPython(populate_monitoring_division_fk),
        # Remove the old CharField fields and rename the FK fields
        migrations.RemoveField(
            model_name='staff',
            name='division',
        ),
        migrations.RemoveField(
            model_name='masterfundmonitoring',
            name='division',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='division_obj',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='masterfundmonitoring',
            old_name='division_obj',
            new_name='division',
        ),
    ]
