# Generated by Django 6.0.2 on 2026-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0037_alter_masterfundmonitoring_purchase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='status',
            field=models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('On Process', 'On Process')], help_text='Transaction status', max_length=20, null=True),
        ),
    ]
