# Generated by Django 6.0.2 on 2026-05-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chathistory',
            new_name='chatbot_app_timesta_732716_idx',
            old_name='chatbot_ch_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='chathistory',
            new_name='chatbot_app_user_id_be9e56_idx',
            old_name='chatbot_ch_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='chathistory',
            new_name='chatbot_app_detecte_21e7f4_idx',
            old_name='chatbot_ch_intent_ts_idx',
        ),
    ]
