# Generated by Django 6.0.2 on 2026-04-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('budget', 'Budget'), ('expense', 'Expense'), ('fund', 'Fund'), ('deadline', 'Deadline'), ('system', 'System'), ('finance', 'Finance'), ('financial_analysis', 'Financial Analysis'), ('finance_monitoring', 'Finance Monitoring'), ('fund_budget', 'Fund/Budget')], default='system', max_length=30),
        ),
    ]
