# Generated by Django 4.2 on 2026-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_notification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seed Run',
                'verbose_name_plural': 'Seed Runs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
