# Generated by Django 6.0.2 on 2026-04-16 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mater_fundmonitor_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterfundmonitoring',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='masterfundmonitoring',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='masterfundmonitoring',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_fundmonitor_cancelled_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterfundmonitoring',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
