# Generated by Django 6.0.2 on 2026-04-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mater_fundmonitor_app', '0002_masterfundmonitoring_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfundmonitoring',
            name='cheque_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
