# Generated by Django 6.0.2 on 2026-02-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expense_object',
        ),
        migrations.DeleteModel(
            name='ExpenseObject',
        ),
    ]
