# Generated by Django 6.0.2 on 2026-03-24 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dashboard_app.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("account_number", models.CharField(max_length=50, unique=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("archive_reason", models.TextField(blank=True, default="")),
                (
                    "date",
                    models.DateField(
                        validators=[
                            dashboard_app.utils.validators.validate_date_not_in_future
                        ]
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "check_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "debit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                        validators=[
                            dashboard_app.utils.validators.validate_transaction_amount
                        ],
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                        validators=[
                            dashboard_app.utils.validators.validate_transaction_amount
                        ],
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Cleared", "Cleared"), ("On Process", "On Process")],
                        default="On Process",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Statement",
                "verbose_name_plural": "Bank Statements",
                "ordering": ["date", "created_at"],
            },
        ),
    ]
