# Generated by Django 6.0.2 on 2026-03-24 03:34

import django.db.models.deletion
from django.db import migrations, models

import dashboard_app.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreakdownCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Breakdown Category",
                "verbose_name_plural": "Breakdown Categories",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Division name (letters and spaces only)",
                        max_length=100,
                        unique=True,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_2_100,
                            dashboard_app.utils.validators.validate_letters_only,
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_2_255
                        ],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#95a5a6",
                        max_length=7,
                        validators=[dashboard_app.utils.validators.validate_hex_color],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_0_500
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_5_50
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_3_255
                        ],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db",
                        max_length=7,
                        validators=[dashboard_app.utils.validators.validate_hex_color],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_0_500
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Expense Object",
                "verbose_name_plural": "Expense Objects",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FundSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_2_100
                        ],
                    ),
                ),
                (
                    "annual_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            dashboard_app.utils.validators.validate_budget_amount
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fund Source",
                "verbose_name_plural": "Fund Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Purchase Type",
                "verbose_name_plural": "Purchase Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_2_200
                        ],
                    ),
                ),
                (
                    "tin",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[
                            dashboard_app.utils.validators.validate_tin_format,
                            dashboard_app.utils.validators.validate_tin_numeric,
                        ],
                    ),
                ),
                (
                    "vat_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NV", "Non-VAT Registered"),
                            ("V", "VAT Registered"),
                            ("—", "N/A"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "philgeps_registration",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        validators=[
                            dashboard_app.utils.validators.validate_alphanumeric_with_spaces
                        ],
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_5_500
                        ],
                    ),
                ),
                (
                    "propprietor",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_2_200
                        ],
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[
                            dashboard_app.utils.validators.validate_phone_number
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["supplier"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_2_100,
                            dashboard_app.utils.validators.validate_letters_only,
                        ],
                    ),
                ),
                (
                    "middle_initial",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        validators=[
                            dashboard_app.utils.validators.validate_letters_only
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            dashboard_app.utils.validators.validate_string_length_2_100,
                            dashboard_app.utils.validators.validate_letters_only,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_members",
                        to="data_management_app.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff Members",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="FundSourceBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            dashboard_app.utils.validators.validate_transaction_amount
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_breakdowns",
                        to="data_management_app.breakdowncategory",
                    ),
                ),
                (
                    "fund_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakdowns",
                        to="data_management_app.fundsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fund Source Breakdown",
                "verbose_name_plural": "Fund Source Breakdowns",
                "ordering": ["fund_source", "category__order", "category__code"],
                "unique_together": {("fund_source", "category")},
            },
        ),
        migrations.CreateModel(
            name="NegosyoCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negosyo_centers",
                        to="data_management_app.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negosyo Center",
                "verbose_name_plural": "Negosyo Centers",
                "ordering": ["district__order", "district__name", "name"],
                "unique_together": {("district", "code")},
            },
        ),
        migrations.CreateModel(
            name="TaxTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vat_goods_5", models.CharField(blank=True, max_length=50)),
                ("vat_services_5", models.CharField(blank=True, max_length=50)),
                ("vat_goods_services_3", models.CharField(blank=True, max_length=50)),
                ("vat_goods_1", models.CharField(blank=True, max_length=50)),
                ("vat_services_2", models.CharField(blank=True, max_length=50)),
                ("vat_rental_5", models.CharField(blank=True, max_length=50)),
                ("vat_prof_fee_10", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_entries",
                        to="data_management_app.purchasetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Table Entry",
                "verbose_name_plural": "Tax Table Entries",
                "ordering": ["purchase_type__name"],
                "unique_together": {("purchase_type",)},
            },
        ),
    ]
